# Numpy Batch Operations [Most Powerfull property of numpy]

To give you a flavor of how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects, I first import NumPy and create a small array:

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

data = a * 10
print(data)


[10 20 30]


In [10]:
data = a + b
print(data)

[5 7 9]


In [14]:
data = a + np.flip(b)
print(data)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.ndim)

[7 7 7]
(3,)
3
int64
1
