# Numpy type Conversion

You can explicitly convert or cast an array from one data type to another using ndarray’s **astype** method:
In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer data type, the decimal part will be truncated:

In [1]:
import numpy as np

data = np.array([1, 2, 3])
print(data)


[1 2 3]


In [2]:
data.dtype

dtype('int64')

In [4]:
data = data.astype(np.float32)
print(data)

[1. 2. 3.]


In [13]:
num_string = np.array(["1.5","3.6","2.1"], dtype=np.str_)
print(num_string)
print(num_string.dtype)


['1.5' '3.6' '2.1']
<U3


In [14]:
num = num_string.astype(np.float32)
print(num)

[1.5 3.6 2.1]
