# Creating Arrays
Table 4.1: Some important NumPy array creation functions

| Function              | Description                                                                                                                                                                                       |
| :-------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `array`               | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying one; copies the input data by default.                     |
| `asarray`             | Convert input to ndarray, but do not copy if the input is already an ndarray.                                                                                                                     |
| `arange`              | Like the built-in `range` but returns an ndarray instead of a list.                                                                                                                               |
| `ones`, `ones_like`   | Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a ones array of the same shape and data type.                                         |
| `zeros`, `zeros_like` | Like `ones` and `ones_like` but producing arrays of 0s instead.                                                                                                                                   |
| `empty`, `empty_like` | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros`.                                                                                          |
| `full`, `full_like`   | Produce an array of the given shape and data type with all values set to the indicated *fill value*; `full_like` takes another array and produces a filled array of the same shape and data type. |
| `eye`, `identity`     | Create a square **N × N** identity matrix (1s on the diagonal and 0s elsewhere).                                                                                                                  |



# Data Types

| Type                                    | Type code          | Description                                                                                       |
| :-------------------------------------- | :----------------- | :------------------------------------------------------------------------------------------------ |
| `int8`, `uint8`                         | `i1`, `u1`         | Signed and unsigned 8-bit (1 byte) integer types                                                  |
| `int16`, `uint16`                       | `i2`, `u2`         | Signed and unsigned 16-bit integer types                                                          |
| `int32`, `uint32`                       | `i4`, `u4`         | Signed and unsigned 32-bit integer types                                                          |
| `int64`, `uint64`                       | `i8`, `u8`         | Signed and unsigned 64-bit integer types                                                          |
| `float16`                               | `f2`               | Half-precision floating point                                                                     |
| `float32`                               | `f4` or `f`        | Standard single-precision floating point; compatible with C `float`                               |
| `float64`                               | `f8` or `d`        | Standard double-precision floating point; compatible with C `double` and Python `float`           |
| `float128`                              | `f16` or `g`       | Extended-precision floating point                                                                 |
| `complex64`, `complex128`, `complex256` | `c8`, `c16`, `c32` | Complex numbers represented by two 32, 64, or 128 floats, respectively                            |
| `bool`                                  | `?`                | Boolean type storing `True` and `False` values                                                    |
| `object`                                | `O`                | Python object type; a value can be any Python object                                              |
| `string_`                               | `S`                | Fixed-length ASCII string type (1 byte per character); e.g., `'S10'` creates length-10 strings    |
| `unicode_`                              | `U`                | Fixed-length Unicode type (platform-dependent bytes); same semantics as `string_` (e.g., `'U10'`) |


In [5]:
from time import process_time

import numpy as np

In [6]:
# creating arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)


[1 2 3]
[4 5 6]


In [7]:
c = np.asarray(a)
print(c)

[1 2 3]


In [12]:
d = np.arange(1,10).reshape((3,3))
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
e = np.ones(3)
print(e)

[1. 1. 1.]


In [17]:
f = np.ones((3,3))
print(f)
print(f.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [18]:
g = np.zeros(9)
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
h = np.zeros((3,3))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
e = np.empty(3)
print(e)

[1. 1. 1.]


In [28]:
e = np.empty((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
f = np.full(3,3)
print(f)

[3 3 3]


In [32]:
f = np.full((3,3),3)
print(f)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
