# Array Arithmetic

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [5]:
print(a/2)
print(a // 2)
print(a % 2)
print(a ** 2)


[0.5 1.  1.5]
[0 1 1]
[1 0 1]
[1 4 9]


In [6]:
print(a > 2)

[False False  True]
