# Array Slicing

<img src="../../images/array_slicing.png" alt="Array Slicing" width="500">

* An important first distinction from Python's built-in lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.
* The "bare" slice [:] will assign to all values in an array

In [1]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
b= np.arange(0,12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b[0:1]

array([[0, 1, 2, 3]])

In [5]:
b[1]

array([4, 5, 6, 7])

In [6]:
b[1,0:2]

array([4, 5])

In [8]:
b[1,0:2] = 5
b

array([[ 0,  1,  2,  3],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Array Indexing & Slicing Combined

<img src="../../images/array_indexing_slicing.png" alt="Array Indexing and Slicing" width="500">

In [10]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
x[:2,1:]

array([[2, 3],
       [5, 6]])

In [13]:
x[2]
x[2, :]
x[2:, :]

array([[7, 8, 9]])

In [14]:
x[:,:2 ]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
x[1:2,:2]
x[1,:2]

array([4, 5])