# Sequence to Array

In [1]:
import numpy as np

In [2]:
ints =  [-2,-1,0.,1,2]
arr1 = np.array(ints)
print(arr1)

[-2. -1.  0.  1.  2.]


In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6]]
                  )
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
matrix_3d = np.array([[[1,2,3]]])
print(matrix_3d)

[[[1 2 3]]]


In [18]:
arr2 = np.array([1,2,3,-1], dtype=np.short)
print(arr2)

[ 1  2  3 -1]


In [16]:
print(arr2.dtype)

int16
