In [1]:
import numpy as np

In [3]:
first_five = np.arange(5)
print(first_five)

[0 1 2 3 4]


In [5]:
start_at_minus_2 = np.arange(-2,3)
print(start_at_minus_2)

[-2 -1  0  1  2]


In [7]:
first_evens = np.arange(0,11, 2)
print(first_evens)

[ 0  2  4  6  8 10]


In [9]:
first_negatives = np.arange(-1,-4, -1)
print(first_negatives)

[-1 -2 -3]


In [12]:
floats = np.arange(0.1,0.6, 0.1, dtype=np.single)
print(floats)

[0.1 0.2 0.3 0.4 0.5]


In [13]:
ln = np.linspace(0.1, 0.5, 5)
print(ln)

[0.1 0.2 0.3 0.4 0.5]
