In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
zeros = np.zeros(3)
print(zeros)

[0. 0. 0.]


In [6]:
z = np.zeros((5,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
one = np.ones((4,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
f = np.full((3,3), 4)
print(f)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [13]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
