# Indexing and Slicing

In [1]:
import numpy as np

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [4]:
print(arr[-1])

4


In [9]:
print(arr[1])

1


In [12]:
arr2d = np.arange(16).reshape(4,4)
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
arr2d[2]

array([ 8,  9, 10, 11])

In [15]:
arr2d[2] = 12

In [16]:
arr2d[2]

array([12, 12, 12, 12])