# Advance Indexing

In [1]:
import numpy as np

In [2]:
arr2d = np.arange(16).reshape(4,4)
print(arr2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
print(arr2d[[1,3]])

[[ 4  5  6  7]
 [12 13 14 15]]


In [6]:
# Boolean Indexing
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [7]:
print(arr[arr >1])

[2 3 4]


In [8]:
print(arr[np.array([True,False,True,False,False])])

[0 2]


In [9]:
# Reshaping

In [11]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
data = np.arange(8).reshape(2,2,2)
data

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
#flattening
data2 = data.reshape(-1)
data2

array([0, 1, 2, 3, 4, 5, 6, 7])