# Broadcasting

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.broadcast_arrays(a, b)
print(c)

(array([1, 2, 3]), array([4, 5, 6]))


In [3]:
d = a + b
print(d)

[5 7 9]


In [5]:
e = a + b.T
print(e)

[5 7 9]


In [6]:
p = np.arange(12).reshape(3, 4)
q = np.arange(12).reshape(3, 4)
print(p)
print(q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
r = p + q.T
print(r)


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 