# nditer

In [1]:
import numpy as np


In [2]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
for element in a:
    print(element)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [4]:
# nditer

for element in np.nditer(a):
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [6]:
# order parameter
for element in np.nditer(a, order='F'):
    print(element)

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


In [8]:
# op_flags parameter - allows modifying while reading
for element in np.nditer(a, op_flags=['readwrite'], order='F'):
    element[...] = 0

print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
# Modify 2 arrays at the same time
p = np.arange(12).reshape(4,3)
q = np.arange(12).reshape(4,3)

for x,y in np.nditer([p,q], op_flags=['readwrite']):
    print(x * y)

0
1
4
9
16
25
36
49
64
81
100
121
