# Elementwise Operation Chaining

<img src="../../images/element_wise_operation_chaining.png" alt="Elementwise operations" width="400">

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../../data/numpy/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000


In [3]:
overall_quality = np.array(df["OverallQual"])[0:10]
overall_quality

array([7, 6, 7, 7, 8, 5, 8, 7, 7, 5])

In [4]:
overall_condition = np.array(df["OverallCond"])[0:10]
overall_condition

array([5, 8, 5, 5, 5, 5, 5, 6, 5, 6])

In [5]:
house_quality = overall_condition * overall_quality
house_quality

array([35, 48, 35, 35, 40, 25, 40, 42, 35, 30])

In [6]:
(overall_condition * overall_quality) ** 2


array([1225, 2304, 1225, 1225, 1600,  625, 1600, 1764, 1225,  900])