# Reshape Operations

<img src="../../images/reshape1.png" alt="Elementwise operations" width="400">

<img src="../../images/reshape2.png" alt="Elementwise operations" width="400">

<img src="../../images/reshape3.png" alt="Elementwise operations" width="400">

<img src="../../images/reshape4.png" alt="Elementwise operations" width="400">

In [4]:
import numpy as np
import pandas as pd
from numpy.ma.core import arange

df = pd.read_csv("../../data/numpy/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000


# Reshaping

In [20]:
sale_price_1d = np.array(df["SalePrice"])[0:12]
sale_price_1d

array([208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000,
       129900, 118000, 129500, 345000])

In [21]:
sale_price_2d = sale_price_1d.reshape((4,3))
sale_price_2d

array([[208500, 181500, 223500],
       [140000, 250000, 143000],
       [307000, 200000, 129900],
       [118000, 129500, 345000]])

In [22]:
sale_price_3d=sale_price_1d.reshape((3,2,2))
sale_price_3d

array([[[208500, 181500],
        [223500, 140000]],

       [[250000, 143000],
        [307000, 200000]],

       [[129900, 118000],
        [129500, 345000]]])

# Flattening

In [23]:
sp_1d = sale_price_3d.flatten()
sp_1d

array([208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000,
       129900, 118000, 129500, 345000])

# Transpose

In [24]:
sale_price_2d

array([[208500, 181500, 223500],
       [140000, 250000, 143000],
       [307000, 200000, 129900],
       [118000, 129500, 345000]])

In [25]:
trans = sale_price_2d.transpose()
trans

array([[208500, 140000, 307000, 118000],
       [181500, 250000, 200000, 129500],
       [223500, 143000, 129900, 345000]])