# 27 - Stack, Split & Concatenate Operations in NumPy

<img src="../../images/concat1.png" alt="Elementwise operations" width="400">

<img src="../../images/concat2.png" alt="Elementwise operations" width="400">

<img src="../../images/split1.png" alt="Elementwise operations" width="400">

<img src="../../images/stack1.png" alt="Elementwise operations" width="400">

In [9]:
import numpy as np

## 1. Concatenate (`np.concatenate`)

Joins arrays along an **existing** axis.

### 1.1 Concatenate 1D arrays

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate([a, b])
print("a:", a)
print("b:", b)
print("concatenate([a, b]):", result)
print("Shape:", result.shape)

a: [1 2 3]
b: [4 5 6]
concatenate([a, b]): [1 2 3 4 5 6]
Shape: (6,)


### 1.2 Concatenate 2D arrays along axis=0 (rows)

In [11]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

result_axis0 = np.concatenate([m1, m2], axis=0)
print("m1:\n", m1)
print("m2:\n", m2)
print("\nconcatenate axis=0 (stack rows):\n", result_axis0)
print("Shape:", result_axis0.shape)

m1:
 [[1 2]
 [3 4]]
m2:
 [[5 6]
 [7 8]]

concatenate axis=0 (stack rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)


### 1.3 Concatenate 2D arrays along axis=1 (columns)

In [12]:
result_axis1 = np.concatenate([m1, m2], axis=1)
print("m1:\n", m1)
print("m2:\n", m2)
print("\nconcatenate axis=1 (stack columns):\n", result_axis1)
print("Shape:", result_axis1.shape)

m1:
 [[1 2]
 [3 4]]
m2:
 [[5 6]
 [7 8]]

concatenate axis=1 (stack columns):
 [[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)


## 2. Stack (`np.stack`, `np.vstack`, `np.hstack`, `np.dstack`)

Joins arrays along a **new** axis (unlike concatenate which uses an existing axis).

### 2.1 `np.stack` — stack along a new axis

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# axis=0: each array becomes a row
stacked_0 = np.stack([a, b], axis=0)
print("stack axis=0:\n", stacked_0)
print("Shape:", stacked_0.shape)

# axis=1: each array becomes a column
stacked_1 = np.stack([a, b], axis=1)
print("\nstack axis=1:\n", stacked_1)
print("Shape:", stacked_1.shape)

stack axis=0:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

stack axis=1:
 [[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


### 2.2 `np.vstack` — vertical stack (row-wise)

Equivalent to `np.concatenate` along axis=0.

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack([a, b])
print("vstack 1D arrays:\n", result)
print("Shape:", result.shape)

# With 2D arrays
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6]])

result_2d = np.vstack([m1, m2])
print("\nvstack 2D arrays:\n", result_2d)
print("Shape:", result_2d.shape)

vstack 1D arrays:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)

vstack 2D arrays:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)


### 2.3 `np.hstack` — horizontal stack (column-wise)

Equivalent to `np.concatenate` along axis=1 for 2D arrays.

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack([a, b])
print("hstack 1D arrays:", result)
print("Shape:", result.shape)

# With 2D arrays
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5], [6]])

result_2d = np.hstack([m1, m2])
print("\nhstack 2D arrays:\n", result_2d)
print("Shape:", result_2d.shape)

hstack 1D arrays: [1 2 3 4 5 6]
Shape: (6,)

hstack 2D arrays:
 [[1 2 5]
 [3 4 6]]
Shape: (2, 3)


### 2.4 `np.dstack` — depth stack (along 3rd axis)

Stacks arrays along axis=2. Useful for combining 2D arrays into a 3D array (e.g., RGB channels).

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

result = np.dstack([m1, m2])
print("m1:\n", m1)
print("m2:\n", m2)
print("\ndstack:\n", result)
print("Shape:", result.shape)

m1:
 [[1 2]
 [3 4]]
m2:
 [[5 6]
 [7 8]]

dstack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape: (2, 2, 2)


## 3. Split (`np.split`, `np.vsplit`, `np.hsplit`, `np.dsplit`)

The inverse of stacking/concatenating — splits an array into multiple sub-arrays.

### 3.1 `np.split` — split into equal parts

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
parts = np.split(arr, 3)
print("Original:", arr)
print("Split into 3 parts:")
for i, part in enumerate(parts):
    print(f"  Part {i}: {part}")

Original: [1 2 3 4 5 6]
Split into 3 parts:
  Part 0: [1 2]
  Part 1: [3 4]
  Part 2: [5 6]


### 3.2 `np.split` with indices — split at specific positions

In [18]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Split at index 2 and 5 → 3 unequal parts
parts = np.split(arr, [2, 5])
print("Original:", arr)
print("Split at indices [2, 5]:")
for i, part in enumerate(parts):
    print(f"  Part {i}: {part}")

Original: [10 20 30 40 50 60 70 80]
Split at indices [2, 5]:
  Part 0: [10 20]
  Part 1: [30 40 50]
  Part 2: [60 70 80]


### 3.3 `np.array_split` — split into unequal parts

Unlike `np.split`, this does not raise an error when the array cannot be evenly divided.

In [19]:
arr = np.array([1, 2, 3, 4, 5])

# 5 elements into 3 parts → unequal sizes
parts = np.array_split(arr, 3)
print("Original:", arr)
print("array_split into 3 parts:")
for i, part in enumerate(parts):
    print(f"  Part {i}: {part}")

Original: [1 2 3 4 5]
array_split into 3 parts:
  Part 0: [1 2]
  Part 1: [3 4]
  Part 2: [5]


### 3.4 `np.vsplit` and `np.hsplit` — split 2D arrays

In [ ]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print("Original (4x4):\n", m)

# vsplit: split along rows (axis=0)
top, bottom = np.vsplit(m, 2)
print("\nvsplit into 2:")
print("Top:\n", top)
print("Bottom:\n", bottom)

# hsplit: split along columns (axis=1)
left, right = np.hsplit(m, 2)
print("\nhsplit into 2:")
print("Left:\n", left)
print("Right:\n", right)

## 4. Summary

| Operation | Function | Description |
|-----------|----------|-------------|
| **Concatenate** | `np.concatenate` | Join along an existing axis |
| **Stack** | `np.stack` | Join along a **new** axis |
| **Vertical Stack** | `np.vstack` | Stack row-wise (axis=0) |
| **Horizontal Stack** | `np.hstack` | Stack column-wise (axis=1) |
| **Depth Stack** | `np.dstack` | Stack along 3rd axis (axis=2) |
| **Split** | `np.split` | Split into equal sub-arrays |
| **Array Split** | `np.array_split` | Split into (possibly unequal) sub-arrays |
| **Vertical Split** | `np.vsplit` | Split along rows (axis=0) |
| **Horizontal Split** | `np.hsplit` | Split along columns (axis=1) |
| **Depth Split** | `np.dsplit` | Split along 3rd axis (axis=2) |