In [1]:
import numpy as np

In [2]:
t = np.linspace(0,10,100)
print(t)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [3]:
x = np.cos(t)
y = np.sin(t)
z = t/2

In [4]:
traj = np.column_stack((x,y,z))
print(traj)

[[ 1.          0.          0.        ]
 [ 0.99490282  0.10083842  0.05050505]
 [ 0.97966323  0.20064886  0.1010101 ]
 [ 0.95443659  0.2984138   0.15151515]
 [ 0.91948007  0.39313661  0.2020202 ]
 [ 0.87515004  0.48385164  0.25252525]
 [ 0.8218984   0.56963411  0.3030303 ]
 [ 0.76026803  0.64960951  0.35353535]
 [ 0.69088721  0.72296256  0.4040404 ]
 [ 0.61446323  0.78894546  0.45454545]
 [ 0.53177518  0.84688556  0.50505051]
 [ 0.44366602  0.8961922   0.55555556]
 [ 0.35103397  0.93636273  0.60606061]
 [ 0.25482335  0.96698762  0.65656566]
 [ 0.15601496  0.98775469  0.70707071]
 [ 0.0556161   0.99845223  0.75757576]
 [-0.04534973  0.99897117  0.80808081]
 [-0.14585325  0.98930624  0.85858586]
 [-0.24486989  0.96955595  0.90909091]
 [-0.34139023  0.93992165  0.95959596]
 [-0.43443032  0.90070545  1.01010101]
 [-0.52304166  0.85230712  1.06060606]
 [-0.60632092  0.79522006  1.11111111]
 [-0.68341913  0.73002623  1.16161616]
 [-0.75355031  0.65739025  1.21212121]
 [-0.81599952  0.57805259